### PR TITLE
fix bindgen failure

### PR DESCRIPTION
**Pull request by Spxg**
fix bindgen failure caused by '__pthread_cond_s_union_ is not a valid Ident'  error
Screenshot 2023-06-24 232559

### CODE REVIEW

**Comment by gierens** [comment]
I do have a similar issue:
Screenshot from 2023-10-02 21-15-39

I fiddled around with the bindgen version and got it working as well ... then I saw this PR and tried that out as well ... Works! Would be great if this was merged or otherwise addressed at some point :)

**Comment by zjykzk** [comment]
i do have a similar issue:

`  thread 'main' panicked at '"in6_addr_union_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX_sdk/usr/include/netinet6/in6_h_153_2)" is not a valid Ident', /Users/admin/.cargo/registry/src/rsproxy.cn
-8f6827c7555bfaf8/proc-macro2-1.0.67/src/fallback.rs:774:9
`

**Comment by bmatcuk** [comment]
Sorry it has taken a while to get to this. You weren't [the first](https://github.com/bmatcuk/libuv-sys/pull/4) to submit a PR to update bindgen - the problem was that the newer version of bindgen generated some different types for some functions, so I was waiting for a new major or minor version of libuv to release, since it's a breaking change in libuv-sys2. But life's been busy the last several months, as these things go...

Anyway, I merged your PR just now and updated to libuv v1.45.0 (I'll do another for v1.46.0 in a little bit, and related updates to libuv-rs, as soon as I figure out why Windows _always_ fails when I update this package, ugh).

**Comment by Spxg** [comment]
> Sorry it has taken a while to get to this. You weren't [the first](https://github.com/bmatcuk/libuv-sys/pull/4) to submit a PR to update bindgen - the problem was that the newer version of bindgen generated some different types for some functions, so I was waiting for a new major or minor version of libuv to release, since it's a breaking change in libuv-sys2. But life's been busy the last several months, as these things go...
> 
> Anyway, I merged your PR just now and updated to libuv v1.45.0 (I'll do another for v1.46.0 in a little bit, and related updates to libuv-rs, as soon as I figure out why Windows _always_ fails when I update this package, ugh).

https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath
image

need link to shell32.dll?

**Comment by Spxg** [comment]
> > Sorry it has taken a while to get to this. You weren't [the first](https://github.com/bmatcuk/libuv-sys/pull/4) to submit a PR to update bindgen - the problem was that the newer version of bindgen generated some different types for some functions, so I was waiting for a new major or minor version of libuv to release, since it's a breaking change in libuv-sys2. But life's been busy the last several months, as these things go...
> > Anyway, I merged your PR just now and updated to libuv v1.45.0 (I'll do another for v1.46.0 in a little bit, and related updates to libuv-rs, as soon as I figure out why Windows _always_ fails when I update this package, ugh).
> 
> https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath image
> 
> need link to shell32.dll?

Great! I notice that you have solved it before this comment in branch 1.45.x.

**Comment by bmatcuk** [comment]
Yup, seems shell32.dll is automatically linked by cmake, so it's not explicitly in libuv's cmake file. I also just released v1.46.0, as well as a version of libuv-rs based on v1.45.0 with one based on v1.46.0 building as I type.

**Pull request merged**
